
version: "3.5"

services:
  server-1.19.4:
    image: itzg/minecraft-server
    ports:
      - 10144:10144
    environment:
      EULA: "TRUE"
      VERSION: "1.19.4"
    restart: always
    volumes:
      - ../../minecraft_server/minecraft:/data